### ISSUE TITLE
Dev docker CPP demo build errors

### ISSUE THREAD

**Issue by bretwitt** [uwsbel/autonomy-research-testbed#152]
Hi all (@AaronYoung5), working on a few CPP demo scripts

Building demos in the ART dev container leads to the following linker errors ([full error](https://pastebin.com/r4ybRGWu)):
```

art@art-chrono:~/art/sim/cpp/build$ sudo make

[ 25%] Building CXX object CMakeFiles/demo_ROS_sensor.dir/demo_ROS_sensor.cpp.o
[ 50%] Linking CXX executable bin/demo_ROS_sensor
/usr/bin/ld: warning: librclcpp.so, needed by /opt/chrono/lib/libChronoEngine_ros.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: librmw.so, needed by /opt/chrono/lib/libChronoEngine_ros.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: librcutils.so, needed by /opt/chrono/lib/libChronoEngine_ros.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libstd_msgs__rosidl_typesupport_cpp.so, needed by /opt/chrono/lib/libChronoEngine_ros.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: liblibstatistics_collector.so, needed by /opt/chrono/lib/libChronoEngine_ros.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: librcl.so, needed by /opt/chrono/lib/libChronoEngine_ros.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: librosgraph_msgs__rosidl_typesupport_cpp.so, needed by /opt/chrono/lib/libChronoEngine_ros.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libstatistics_msgs__rosidl_typesupport_cpp.so, needed by /opt/chrono/lib/libChronoEngine_ros.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libtracetools.so, needed by /opt/chrono/lib/libChronoEngine_ros.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libgeometry_msgs__rosidl_typesupport_cpp.so, needed by /opt/chrono/lib/libChronoEngine_ros.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libsensor_msgs__rosidl_typesupport_cpp.so, needed by /opt/chrono/lib/libChronoEngine_ros.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libtf2_ros.so, needed by /opt/chrono/lib/libChronoEngine_ros.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libtf2_msgs__rosidl_typesupport_cpp.so, needed by /opt/chrono/lib/libChronoEngine_ros.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libchrono_ros_interfaces__rosidl_typesupport_cpp.so, needed by /opt/chrono/lib/libChronoEngine_ros.so, not found (try using -rpath or -rpath-link)

```

Before that command I did a typical ```cmake ..```

Wondering what could be happening, here's the $LD_LIBRARY_PATH which includes the paths that include the *.so files it's looking for
```

art@art-chrono:~/art/sim/cpp/build$ echo $LD_LIBRARY_PATH
/home/art/ros_workspace/install/chrono_ros_interfaces/lib:/opt/ros/humble/lib/x86_64-linux-gnu:/opt/ros/humble/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/opt/chrono/lib:/opt/urdf/lib:/opt/vsg/lib

```

Would appreciate any guidance!

**Comment by AaronYoung5** [comment]
When you use `sudo`, you're using a different environment, as in the `$LD_LIBRARY_PATH` will be different from what you just echoed. And so then the sourced ROS environment variables won't be present in the sudo env (even tho they are present in the base user's shell). And do you need sudo? Inside the ART repo, you shouldn't need sudo because this will cause filesystem access issues outside the container. So I would recommend not using sudo there, and just do make (or ninja preferably, can ask around if you're not sure what that is).

So the steps would be:

1. Remove `art/sim/cpp/build` (probably will need sudo since some of the files were made by the root user when you ran sudo).
2. `cd art/sim/cpp/ && mkdir build && cd build && cmake -GNinja .. && ninja`

The above assumes the ROS distribution has already been sourced (should be done already since it's in the `~/.bashrc` file).

@bretwitt lmk if that makes sense or if I should clarify anything!! And I might be wrong, so lmk if that's also the case and I can jump on a call!

**Comment by bretwitt** [comment]
Lol, yikes, can't believe I missed that. Thanks, it worked!
