### ISSUE TITLE
Fail to build art-chrono container

### ISSUE THREAD

**Issue by harryzhang1018** [uwsbel/autonomy-research-testbed#25]
@AaronYoung5 When I build art-chrono container, seems I can't config the chrono at the "cmake ../ -G Ninja" step. Did you have the same issue?
![Screenshot from 2023-09-04 18-26-24](https://github.com/uwsbel/autonomy-research-testbed/assets/79550723/350bebcf-4747-4a89-8cf9-53986cf7293d)

**Comment by StefanCaldararu** [comment]
I have the same issue atm, here is the error:

failed to solve: process "/bin/sh -c cd chrono/build && cmake ../ -G Ninja  -DCMAKE_BUILD_TYPE=Release  -DBUILD_BENCHMARKING=OFF  -DBUILD_DEMOS=OFF  -DBUILD_TESTING=OFF  -DENABLE_MODULE_IRRLICHT=ON  -DENABLE_MODULE_POSTPROCESS=ON  -DENABLE_MODULE_PYTHON=ON  -DENABLE_MODULE_SENSOR=ON  -DENABLE_OPENMP=ON  -DENABLE_MODULE_VEHICLE=ON  -DEigen3_DIR=/usr/lib/cmake/eigen3  -DOptiX_INCLUDE=/opt/optix75/include  -DOptiX_INSTALL_DIR=/opt/optix75  -DNUMPY_INCLUDE_DIR=/usr/lib/python3/dist-packages/numpy/core/include  && ninja && sudo ninja install" did not complete successfully: exit code: 1
CRITICAL | dev._run_dev :: Got an error code of '17': /usr/bin/docker compose -p art -f /home/scaldararu/Documents/autonomy-research-testbed/.atk-compose.yml up -d chrono

And the full output: 
[output.txt](https://github.com/uwsbel/autonomy-research-testbed/files/12528070/output.txt)

**Comment by StefanCaldararu** [comment]
@harryzhang1018 the fix for this is you need to comment out line 61 in `chono/cmake/FindThrust.cmake`. This line is: `string( REGEX MATCH "^[0-9]" minor ${version} )`. Hopefully this will be fixed with Chrono soon. @AaronYoung5 to recreate this issue you need to prune your images - I wasn't able to recreate it for a while because I was using old Chrono builds. I don't think this is an ART/ATK issue so making changes in the `chrono.dockerfile` doesn't make sense (IMO).
